FROM node:18-alpine3.21 AS builder

WORKDIR /app 

COPY package.json .
 
RUN npm install
COPY . . 

RUN npm run build

FROM nginx:stable-alpine3.21-slim AS runtime
COPY --from=builder /app/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]