FROM node:18-alpine3.21 AS build
WORKDIR /app 
COPY package.json ./ 
RUN npm install
RUN npm run build
FROM nginx:stable-alpine3.21-slim
COPY --from=build /app/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
