services:
  backend:
    image: backend-app:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@172.31.38.85:5432/microservices_db

  frontend:
    image: frontend-app:latest
    ports:
      - "80:80"
    depends_on:
      - backend
