services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
  db:
   image: postgres:15-alpine
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=microservices_db
   volumes:
     - pgdata:/var/lib/postgrsql/data
volumes:
  pgdata:
