FROM python:3.10.17-alpine AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt --target=/install

FROM  python:3.10.17-alpine AS runtime

WORKDIR /app

COPY --from=builder /install /usr/local

RUN pip install --upgrade pip && pip install setuptools==78.1.1

COPY . . 

EXPOSE 5000

CMD [ "python", "app.py" ]
