FROM python:3.10.17-alpine as builder

WORKDIR /app
COPY requirements.txt .
RUN python -m venv /opt/venv \
    && . /opt/venv/bin/activate \
    && pip install --upgrade pip \
    && pip install -r requirements.txt

COPY . .

FROM python:3.10.17-alpine

ENV PATH="/opt/venv/bin:$PATH"
WORKDIR /app

COPY --from=builder /opt/venv /opt/venv
COPY . .

EXPOSE 5000
CMD ["python", "app.py"]