FROM python:3.10.17-alpine3.20 AS builder
WORKDIR /app
COPY requirements.txt .
RUN apk add --no-cache build-base && pip install --perfix=/install -r requirements.txt

FROM  python:3.10.17-alpine3.20 AS runtime
WORKDIR /app
COPY --from=builder /install /usr/local
COPY . . 
EXPOSE 5000
CMD [ "python", "app.py" ]
